### ISSUE TITLE
Have someone new to NES development give feedback on first_nes

### ISSUE THREAD

**Issue by gregkrsak** [gregkrsak/first_nes#28]
Let's introduce an experienced programmer (but new NES developer) to first_nes and get their feedback on what could improve.

How easy was the code to dive into?
Does this project give you a good start to NES development?
etc. etc.

This person should (ideally) be familiar with their operating system and making/building in general.

**Comment by gregkrsak** [comment]
@ericandrewlewis would you be willing to comment here?

**Comment by ericandrewlewis** [comment]
@gregkrsak - Sure - for what my notes might be worth!

I came to look at your project after going through Easy 6502, Nerdy Nights NES development tutorials, and random other resources. That is to say I had some context about NES dev before coming across this gem.

The install and setup instructions were easy to follow for Mac OS.

I think you could remove comments that are repeated in each file header. I found it a bit noisey when jumping around reading files. The file-specific documentation is useful and should stay, but for example in [basic_movement.s](https://github.com/gregkrsak/first_nes/blob/master/lib/sprite/basic_movement.s), the file could start:

```asm
; Veryt simple sprite movement routines, for demonstration purposes only.

; ==========================================
; Subroutine to move the Luigi sprites right
; ==========================================

.PROC     MoveLuigiRight
```
et cetera. All the other information I would expect to find in a project's README file.

> How easy was the code to dive into?

I thought the code was relatively easy to dive into...but I did have a lot of context coming in to the project as I mentioned.

> Does this project give you a good start to NES development?

I'm not sure, because I am still so new to all of this. I do think having a boilerplate repository for nes development on ca65 is very useful. A search for "ca65 nes boilerplate" is what led me to the repo.

**Comment by electronoob** [comment]
hi,

code compiled fine without any issues etc. used higan to run the rom and sprite moved as expected.
i had a look around the code. 

im not sure what there is to really say at this point. but i did record a video of me downloading and looking through the code a bit.

https://www.youtube.com/watch?v=jX3UNliLoCo

i dont think it will offer any kind of insight but just in case it is useful to you.

**Comment by electronoob** [comment]
follow up:

So, i'm going through the nerdy night tutorials and having your codebase to support it has been helpful. I was easily able to duplicate the luigi sprite, and move the two sprites in opposite directions. which felt like a win.

**Comment by electronoob** [comment]
I also concur with @ericandrewlewis regarding the noisy header information in the files.

**Comment by gregkrsak** [comment]
Fantastic-- thank you. I'll find time to work on the header issue.
