### ISSUE TITLE
Cannot make first_nes

### ISSUE THREAD

**Issue by mroberts1** [gregkrsak/first_nes#61]
I'm on MacOS 10.15. After cloning repo, here's what happens when I make:

❯ make
rm -f bin/*.bin && rm -f first_nes.nes && rm -f first_nes.o
ca65 --cpu 6502 first_nes.s
make: ca65: No such file or directory
make: *** [assemble] Error 1

**Comment by gregkrsak** [comment]
Thanks for the report. Did you follow the Mac OS quick start instructions in the README?

**Comment by gregkrsak** [comment]
@mroberts1 can you confirm that you've followed the Mac OS instructions in this project's readme, installed cc65 as directed, and ca65 is still unavailable?

**Comment by JamesSkemp** [comment]
For what it's worth, on 10.15.6, following your instructions, it does make the .nes file correctly.

However, the link to download Nestopia .dmg doesn't work (tried the link directly from their site as well).

I opted to use OpenEmu and the `A` and `B` buttons aren't actually moving the character. But he shows up. :)

**Comment by gregkrsak** [comment]
Roger that. Will take a look. Thanks!

**Comment by gregkrsak** [comment]
It looks like the link points to an .APP instead of a .DMG file. I apologize for the confusion. I'll get this fixed as soon as possible.

@JamesSkemp and @mroberts1 -- As I don't have a Mac, can you confirm that you're able to install Nestopia via the README link for Mac OS, but using it as an .APP instead of a .DMG?

**Comment by gregkrsak** [comment]
(See issue #62 moving forward)
